/**
 * NVIDIA judge adapter.
 *
 * Uses the NVIDIA API for judge evaluation.
 */

import type { JudgeAdapter, JudgeInput, JudgeResult } from './types.js';

const NVIDIA_BASE_URL = 'https://integrate.api.nvidia.com/v1';

const JUDGE_SYSTEM_PROMPT = `You are a rigorous evaluation judge. You will be given:
1. A user query
2. An answer generated by an AI system
3. The expected/reference answer
4. The context (retrieved memories) used to generate the answer

Evaluate the answer on four dimensions and return JSON:
{
  "correct": boolean,
  "grounded": boolean,
  "stale": boolean,
  "should_abstain": boolean,
  "confidence": number,
  "reasoning": string
}

Rules:
- "correct" means the answer conveys the same meaning as expected
- "grounded" means the answer can be traced to specific memories in context
- "stale" is true ONLY if the answer contradicts newer information
- "should_abstain" is true if the context doesn't contain enough info
- Return ONLY the JSON object, no markdown fences`;

export function createNVIDIAJudgeAdapter(
  model: string = 'poolside/laguna-xs-2.1',
  apiKey?: string,
): JudgeAdapter {
  const key = apiKey || process.env.NVIDIA_API_KEY;
  if (!key) throw new Error('NVIDIA_API_KEY required for NVIDIA judge adapter');

  return {
    name: `nvidia:${model}`,

    async judge(input: JudgeInput): Promise<JudgeResult> {
      const started = Date.now();

      const contextBlock = input.context.length > 0
        ? input.context.map((c, i) => `[${i + 1}] ${c}`).join('\n\n')
        : 'No context provided.';

      const userPrompt = `Query: ${input.query}

Context:
${contextBlock}

Expected: ${input.expected}

Generated: ${input.answer}

Evaluate. Return JSON only.`;

      const response = await fetch(`${NVIDIA_BASE_URL}/chat/completions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${key}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: JUDGE_SYSTEM_PROMPT },
            { role: 'user', content: userPrompt },
          ],
          temperature: 0.0,
          max_tokens: 512,
          stream: false,
        }),
      });

      if (!response.ok) {
        const err = await response.text();
        throw new Error(`NVIDIA judge API error ${response.status}: ${err}`);
      }

      const data = await response.json() as any;
      const content = data.choices[0].message.content.trim();
      const latencyMs = Date.now() - started;

      try {
        const parsed = JSON.parse(content);
        return {
          correct: Boolean(parsed.correct),
          grounded: Boolean(parsed.grounded),
          stale: Boolean(parsed.stale),
          shouldAbstain: Boolean(parsed.should_abstain),
          confidence: Number(parsed.confidence) || 0.5,
          reasoning: String(parsed.reasoning || ''),
          latencyMs,
        };
      } catch {
        return {
          correct: false,
          grounded: false,
          stale: false,
          shouldAbstain: false,
          confidence: 0,
          reasoning: `Failed to parse judge output: ${content}`,
          latencyMs,
        };
      }
    },
  };
}
