/**
 * OpenAI judge adapter.
 *
 * Uses a stronger model (gpt-4o) to evaluate answer correctness, groundedness,
 * staleness, and abstention. Separate from the answer model to avoid
 * self-evaluation bias.
 */

import type { JudgeAdapter, JudgeInput, JudgeResult } from './types.js';

const OPENAI_BASE_URL = 'https://api.openai.com/v1';

const JUDGE_SYSTEM_PROMPT = `You are a rigorous evaluation judge. You will be given:
1. A user query
2. An answer generated by an AI system
3. The expected/reference answer
4. The context (retrieved memories) used to generate the answer

Evaluate the answer on four dimensions and return JSON:
{
  "correct": boolean,       // Does the answer match the expected answer?
  "grounded": boolean,      // Is the answer supported by the retrieved context?
  "stale": boolean,         // Does the answer contradict newer/updated information?
  "should_abstain": boolean, // Should the system have abstained (query is unanswerable)?
  "confidence": number,     // Your confidence in this assessment (0-1)
  "reasoning": string       // Brief explanation
}

Rules:
- "correct" means the answer conveys the same meaning as expected, not exact word match
- "grounded" means the answer can be traced to specific memories in context
- "stale" is true ONLY if the answer contradicts information from a newer memory
- "should_abstain" is true if the context doesn't contain enough info to answer
- Be strict but fair: partial matches are not "correct"
- Return ONLY the JSON object, no markdown fences`;

export function createOpenAIJudgeAdapter(
  model: string = 'gpt-4o',
  apiKey?: string,
): JudgeAdapter {
  const key = apiKey || process.env.OPENAI_API_KEY;
  if (!key) throw new Error('OPENAI_API_KEY required for OpenAI judge adapter');

  return {
    name: `openai:${model}`,

    async judge(input: JudgeInput): Promise<JudgeResult> {
      const started = Date.now();
      const maxRetries = 5;

      const contextBlock = input.context.length > 0
        ? input.context.map((c, i) => `[${i + 1}] ${c}`).join('\n\n')
        : 'No context provided.';

      const userPrompt = `Query: ${input.query}

Context (retrieved memories):
${contextBlock}

Expected answer: ${input.expected}

Generated answer: ${input.answer}

Evaluate the generated answer. Return JSON only.`;

      for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
          const response = await fetch(`${OPENAI_BASE_URL}/chat/completions`, {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${key}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              model,
              messages: [
                { role: 'system', content: JUDGE_SYSTEM_PROMPT },
                { role: 'user', content: userPrompt },
              ],
              temperature: 0.0,
              max_tokens: 512,
              response_format: { type: 'json_object' },
            }),
          });

          if (response.status === 503 || response.status === 429) {
            const waitTime = Math.min(Math.pow(2, attempt) * 3000, 60000);
            await new Promise(r => setTimeout(r, waitTime));
            continue;
          }

          if (!response.ok) {
            const err = await response.text();
            throw new Error(`OpenAI judge API error ${response.status}: ${err}`);
          }

          const data = await response.json() as any;
          const content = data.choices[0].message.content.trim();
          const latencyMs = Date.now() - started;

          try {
            const parsed = JSON.parse(content);
            return {
              correct: Boolean(parsed.correct),
              grounded: Boolean(parsed.grounded),
              stale: Boolean(parsed.stale),
              shouldAbstain: Boolean(parsed.should_abstain),
              confidence: Number(parsed.confidence) || 0.5,
              reasoning: String(parsed.reasoning || ''),
              latencyMs,
            };
          } catch {
            return {
              correct: false,
              grounded: false,
              stale: false,
              shouldAbstain: false,
              confidence: 0,
              reasoning: `Failed to parse judge output: ${content}`,
              latencyMs,
            };
          }
        } catch (error) {
          if (attempt === maxRetries - 1) throw error;
          await new Promise(r => setTimeout(r, Math.pow(2, attempt) * 2000));
        }
      }

      throw new Error('Max retries exceeded');
    },
  };
}
