/**
 * Memories table schema for migrations
 * Column definitions for ALTER TABLE migrations
 */

import type { TableSchema } from './generator.js';

export const memoriesSchema: TableSchema = {
  name: 'memories',
  columns: {
    id: { type: 'TEXT', primary: true },
    project_id: { type: 'TEXT' },
    user_id: { type: 'TEXT' },
    type: { type: 'TEXT' },
    content: { type: 'TEXT' },
    summary: { type: 'TEXT' },
    embedding_json: { type: 'TEXT' },
    embedding: { type: 'BLOB' },
    // Batch 4: primary float32 LE blob storage + model provenance stamps
    embedding_blob: { type: 'BLOB' },
    embedding_model: { type: 'TEXT' },
    embedding_dim: { type: 'INTEGER' },
    source: { type: 'TEXT' },
    confidence: { type: 'INTEGER', default: '50' },
    confidence_level: { type: 'TEXT', default: "'speculative'" },
    tags: { type: 'TEXT' },
    metadata: { type: 'TEXT' },
    is_private: { type: 'INTEGER', default: '0' },
    has_secrets: { type: 'INTEGER', default: '0' },
    relevance_score: { type: 'INTEGER', default: '50' },
    is_active: { type: 'INTEGER', default: '1' },
    expires_at: { type: 'INTEGER' },
    access_count: { type: 'INTEGER', default: '0' },
    last_accessed_at: { type: 'INTEGER' },
    is_merged: { type: 'INTEGER', default: '0' },
    merged_into_id: { type: 'TEXT' },
    merged_at: { type: 'INTEGER' },
    is_canonical: { type: 'INTEGER', default: '0' },
    merge_source_ids: { type: 'TEXT' },
    is_mergeable: { type: 'INTEGER', default: '1' },
    merge_version: { type: 'INTEGER', default: '1' },
    namespace_id: { type: 'TEXT' },
    namespace_path: { type: 'TEXT' },
    has_l0_abstract: { type: 'INTEGER', default: '0' },
    has_l1_overview: { type: 'INTEGER', default: '0' },
    last_layer_update: { type: 'INTEGER' },
    importance_score: { type: 'INTEGER', default: '50' },
    importance_decay_rate: { type: 'INTEGER', default: '30' },
    last_importance_recalc: { type: 'INTEGER' },
    retrieval_priority: { type: 'INTEGER', default: '50' },
    tokens_estimate: { type: 'INTEGER', default: '0' },
    consolidated_into: { type: 'TEXT' },
    consolidated_at: { type: 'INTEGER' },
    is_consolidated: { type: 'INTEGER', default: '0' },
    sector: { type: 'TEXT', default: "'episodic'" },
    tier: { type: 'TEXT', default: "'hot'" },
    status: { type: 'TEXT', default: "'active'" },
    encrypted_content: { type: 'TEXT' },
    encryption_nonce: { type: 'TEXT' },
    is_encrypted: { type: 'INTEGER', default: '0' },
    context_status: { type: 'TEXT', default: "'out-of-context'" },
    decay_rate: { type: 'INTEGER', default: '30' },
    coactivation_score: { type: 'INTEGER', default: '0' },
    last_decay_at: { type: 'INTEGER' },
    agent_id: { type: 'TEXT' },
    agent_role: { type: 'TEXT' },
    visibility_scope: { type: 'TEXT', default: "'private'" },
    is_protected: { type: 'INTEGER', default: '0' },
    is_pinned: { type: 'INTEGER', default: '0' },
    is_immutable: { type: 'INTEGER', default: '0' },
    write_scope: { type: 'TEXT' },
    read_scope: { type: 'TEXT' },
    triggered_by: { type: 'TEXT' },
    capture_reason: { type: 'TEXT' },
    last_used_at: { type: 'INTEGER' },
    usage_count: { type: 'INTEGER', default: '0' },
    valid_from: { type: 'INTEGER' },
    valid_to: { type: 'INTEGER' },
    recorded_at: { type: 'INTEGER' },
    superseded_by: { type: 'TEXT' },
    stability: { type: 'REAL', default: '0.0' },
    last_reinforced_at: { type: 'INTEGER' },
    version: { type: 'INTEGER', default: '1' },
    place_id: { type: 'TEXT' },
    place_sort_order: { type: 'INTEGER', default: '0' },
    // v1.5.0: Multi-place routing
    primary_place: { type: 'TEXT' },
    memory_type: { type: 'TEXT' },
    // v2.0.0: Multimodal ingestion
    media_type: { type: 'TEXT' },
    media_path: { type: 'TEXT' },
    media_metadata: { type: 'TEXT' },
    created_at: { type: 'INTEGER' },
    updated_at: { type: 'INTEGER' },
  },
};
